apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernates.io/instance: argo-test
  name: my-nginx
  namespace: test
spec:
  replicas: 8 # 원하는 레플리카 수로 설정하세요.
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
        - name: my-nginx-container
          image: docker.io/kkycake/my-nginx:1.2
          # Docker Hub 사용자 이름, 이미지 이름 및 원하는 태그를 여기에 입력하세요.
          ports:
            - containerPort: 80 # 컨테이너가 리스닝하는 포트를 설정하세요.
